### ISSUE TITLE
Sell Usage Bug

### ISSUE THREAD

**Issue by LavaisWatery** [LucidLLC/Teams-Issues#11]
#### IGN
> Cha' Boy LavaisWatery

#### Expected behavior
> When I type /sell all it should maybe sell my whole hand but that isn't relevant

#### Current behavior
> When I type /sell all it comes up with the /buy usage

#### Possible solutions (optional)
> Maybe make all another alias for 'hand' or change the usage so it's not so confusing.

#### Steps to reproduce (optional)
> 1. Open minecraft 1.7.10 or 1.8.8 if you're a normie
> 2. Login to dreamz.io
> 3. Click the 'Server Teleporter' item
> 4. Make sure you click the 'Main' itemstack.
> 5. Hit your chat key and type /sell all or /sell mylife
> 6. Hit ENTER!
> 7. You will see that the usage is wrong. 

#### Other information (optional, screenshots)
> https://gyazo.com/1b1e47457dcf919fb4a45e5ec7482c75

**Comment by rbrick** [comment]
I can't reproduce. My keyboard doesn't have an enter key

**Comment by ItsLostNZ** [comment]
/sell hand sells all items in inventory instead of the one stack (at least for blocks/ores). You can't sell multiple soup when doing /sell 5 says "not enough items"

**Comment by ItsLostNZ** [comment]
Founded by Nernnn (confirmed by myself) 
Selling a swp2 potion sells all potions within inventory. Will check if this can be abused with water bottles//mundane potions. Potentially sells fire res (with the swp2/strp2 bug)
