### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by dblucc** [LucidLLC/Teams-Issues#17]
#### IGN
> TheDiamondBlock

#### Expected behavior
> Scoreboard doesn't disappear when I do /hud

#### Current behavior
> Scoreboard is static and just sits there

#### Other information (optional, screenshots)
> /hud

**Comment by LavaisWatery** [comment]
wth that's not realistic, this server is perfect!

**Comment by juIio** [comment]
@YoungOG
