### ISSUE TITLE
StaffMode inventory book bug.

### ISSUE THREAD

**Issue by JessePepper69** [LucidLLC/Teams-Issues#2]
#### IGN
> Indefensive

#### Expected behavior
> Check inventory to auto update as a player does an action ( related to the inventory )

#### Current behavior
> Once you open a players inventory using the staff mode book it will only save and display the position the inventory was as you opened it, it does not update if a user drops an item or uses a soup ect.

#### Possible solutions (optional)
> i dont have any i dont code java

#### Steps to reproduce (optional)
> 
1. Fill a players inventory
2. Go in staff mode and open the players inventory using the inventory book
3. Tell the person to drop all the items in there inventory
4. Boom, all the items are out of there inventory but it still shows them in the inventory book

#### Other information (optional, screenshots)
> i dont have any ( but its very easy to replicate )

**Comment by ItsLostNZ** [comment]
Addition to the bug:
Bowls will go into one stack and make it look like auto soup (watched a fight between an admin and a legit player where same thing occurred).
