### ISSUE TITLE
Random TP bug

### ISSUE THREAD

**Issue by JessePepper69** [LucidLLC/Teams-Issues#21]
#### IGN
> Kelimutu

#### Expected behavior
> Random tp to work for everyone that has the ability to tp past 0, 0 (Mod >)

#### Current behavior
> When you right click the random tp disk it then says "You cannot teleport past 0 of x:0 z:0"

#### Possible solutions (optional)
> Not sure of any solutions but I do know it happens to only work for people with platform admin or higher, making me think the only reason they can do it is due to having OP

#### Steps to reproduce (optional)
1) Must not be op
2) Go into mod mode
3) Right click random tp disk

**Comment by rbrick** [comment]
missing permission node
