### ISSUE TITLE
StaffMode block glitch

### ISSUE THREAD

**Issue by JessePepper69** [LucidLLC/Teams-Issues#3]
#### IGN
> Indefensive

#### Expected behavior
> Stop items from being activated when you step on certain types of blocks

#### Current behavior
> When you're in mod mode and you stop on a crop or staff on a pressure plate it will use the item you're holding. Ex. If i'm in vanish and im holding the vanish dye in my hand, then i stanf on a pressure plate it will disable my vanish as if i pressed it.

#### Possible solutions (optional)
> Make it so you HAVE to right click the item for it to be used.

#### Steps to reproduce (optional)
>
1. Go in mod mode
2. Go into vanish
3. Hold the vanish dye in your hand
4. Stop on a crop or pressure plate
5. You'll automatically be removed from vanish because it for some reason clicks the item you're holding

#### Other information (optional, screenshots)
> Im sure this works with other blocks, but ive only been able to test Crops and Pressure plates

**Comment by juIio** [comment]
The issue with this is not checking which action is being made inside the PlayerInteractEvent, causing even physical events to toggle the dye in your scenario.
Thanks for letting us know, fixing soon!
